name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup install stable          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Lint
        run: |
          cargo fmt -- --check

      - name: Test
        run: |
          cargo test --all          

      - name: Build
        run: |
          cargo build --release