name: Tag release

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  tag:
    name: Tag release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: version
        run: ./tag.sh